name: CI/CD test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt update -y && sudo apt-get install gcc g++ make cmake
      - run: make clean
      - run: make -B app
      - uses: actions/upload-artifact@v3
        with:
          name: app-bin
          path: eq_solver
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: app-bin
      - run: sudo apt update -y && sudo apt-get install gcc g++ make cmake
      - run: cat .gitmodules
      - run: git submodule init
      - run: git submodule update --init
      - run: make test
    
